package com.mulesoft.training;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;

public class DBInitialization implements InitializingBean {
	private static Logger logger = LoggerFactory.getLogger(DBInitialization.class);
	private static boolean init = false;
	public void afterPropertiesSet() throws Exception {
		String dbURL = "jdbc:derby:memory:muleEmbeddedDB;create=true";
		Connection conn = null;
		try {
			Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
			// Get a connection
			conn = DriverManager.getConnection(dbURL);
			Statement stmt = conn.createStatement();
//			if(i!=1){
			try {
				stmt.execute("SELECT * FROM Account");
			}
			catch(SQLException ex) {
			stmt.executeUpdate("CREATE TABLE Account(accountID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY," +
					"name VARCHAR(120)," +
					"street VARCHAR(180)," +
					"city VARCHAR(120)," +
					"country VARCHAR(120)," +
					"state VARCHAR(120)," +
					"postal VARCHAR(120))");
			stmt.executeUpdate("INSERT INTO Account(name, street, city, country, state, postal) VALUES ('Aero Wheels','127 Welding Blvd','Seattle','United States','Washington','98101')");
			stmt.executeUpdate("INSERT INTO Account(name, street, city, country, state, postal) VALUES ('Aero Wings','149 Welding Blvd','Seattle','United States','Washington','98101')");
			stmt.executeUpdate("INSERT INTO Account(name, street, city, country, state, postal) VALUES ('Aero Doors','964 Welding Blvd','Seattle','United States','Washington','98101')");
			
			stmt.executeUpdate("CREATE TABLE currentFlights(flightCode VARCHAR(80) NOT NULL PRIMARY KEY," +
					"airlineName VARCHAR(120)," +
					"destination VARCHAR(5)," +
					"origination VARCHAR(5)," +
					"departureDate DATE," +
					"price INT," +
					"planeType VARCHAR(80)," +
					"availableSeats INT)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree4567','American Airlines','SFO','MUA','2015-01-20',456,'Boeing 737',100)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree0123','American Airlines','CLE','MUA','2015-01-25',300,'Boeing 747',7)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree4511','American Airlines','LAX','MUA','2015-01-15',900,'Boeing 777',100)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree0001','American Airlines','LAX','MUA','2015-01-20',541,'Boeing 787',500)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree0192','American Airlines','LAX','MUA','2015-01-20',300,'Boeing 777',75)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree3980','American Airlines','SFO','MUA','2015-02-01',900,'Boeing 737',76)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree2000','American Airlines','SFO','MUA','2015-02-20',300,'Boeing 737',30)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree3000','American Airlines','SFO','MUA','2015-02-01',900,'Boeing 737',76)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree1000','American Airlines','CLE','MUA','2015-01-20',200,'Boeing 737',5)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree1093','American Airlines','SFO','MUA','2015-02-11',142,'Boeing 737',0)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree1112','American Airlines','CLE','MUA','2015-01-20',954,'Boeing 787',100)");
			stmt.executeUpdate("INSERT INTO currentFlights(flightCode, airlineName, destination, origination, departureDate, price, planeType, availableSeats) VALUES ('rree1994','American Airlines','SFO','MUA','2015-01-01',676,'Boeing 777',0)");
			}
			
			init = true;
		
		} 
		catch (java.sql.SQLException sqle) {
			sqle.printStackTrace();
			throw sqle;
		}
	}
}
